// Generated by Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import ObjectiveC;
@import Foundation;
#endif

#import <HDLSDK/HDLSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HDLSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class AirCtrlBackInfo;

SWIFT_PROTOCOL("_TtP6HDLSDK14ACCtrlDelegate_")
@protocol ACCtrlDelegate
- (void)getAirCtrlInfoWithAirCtrlBackInfo:(AirCtrlBackInfo * _Nonnull)airCtrlBackInfo;
@end

@class AppliancesInfo;

SWIFT_CLASS("_TtC6HDLSDK15AirCtrlBackInfo")
@interface AirCtrlBackInfo : NSObject
@property (nonatomic, strong) AppliancesInfo * _Nullable appliancesInfo;
@property (nonatomic, copy) NSString * _Nonnull remarks;
@property (nonatomic) NSInteger isOn;
@property (nonatomic) NSInteger refTemp;
@property (nonatomic) NSInteger airSpeed;
@property (nonatomic) NSInteger airMode;
@property (nonatomic) NSInteger heatTemp;
@property (nonatomic) NSInteger autoTemp;
@property (nonatomic) NSInteger upTemp;
@property (nonatomic) NSInteger downTemp;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull arrCurState;
@property (nonatomic) BOOL isSuccessCtrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK13AirCtrlParser")
@interface AirCtrlParser : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) AirCtrlParser * _Nonnull shareInstance;)
+ (AirCtrlParser * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSInteger fail;
@property (nonatomic, readonly) NSInteger infrared;
@property (nonatomic, readonly) NSInteger panelLock;
@property (nonatomic, readonly) NSInteger airSwich;
@property (nonatomic, readonly) NSInteger airOn;
@property (nonatomic, readonly) NSInteger airOff;
@property (nonatomic, readonly) NSInteger refTem;
@property (nonatomic, readonly) NSInteger airSpeed;
@property (nonatomic, readonly) NSInteger airSpeedAuto;
@property (nonatomic, readonly) NSInteger airSpeedHigh;
@property (nonatomic, readonly) NSInteger airSpeedMid;
@property (nonatomic, readonly) NSInteger airSpeedLow;
@property (nonatomic, readonly) NSInteger airMode;
@property (nonatomic, readonly) NSInteger airModeRefTem;
@property (nonatomic, readonly) NSInteger airModeHeatTem;
@property (nonatomic, readonly) NSInteger airModeVen;
@property (nonatomic, readonly) NSInteger airModeAuto;
@property (nonatomic, readonly) NSInteger airModeDehum;
@property (nonatomic, readonly) NSInteger heatTem;
@property (nonatomic, readonly) NSInteger autoTem;
@property (nonatomic, readonly) NSInteger upTem;
@property (nonatomic, readonly) NSInteger downTem;
@property (nonatomic, readonly) NSInteger dehumTem;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (NSArray<NSNumber *> * _Nonnull)getAirAddByteWithType:(NSInteger)type arg2:(NSInteger)arg2 SWIFT_WARN_UNUSED_RESULT;
@end

@class LogicMode;

SWIFT_CLASS("_TtC6HDLSDK14AppliancesInfo")
@interface AppliancesInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull deviceName;
@property (nonatomic) NSInteger bigType;
@property (nonatomic) NSInteger littleType;
@property (nonatomic) NSInteger ctrlCommand;
@property (nonatomic) NSInteger ctrlBackCommand;
@property (nonatomic) NSInteger stateCommand;
@property (nonatomic) NSInteger stateBackCommand;
@property (nonatomic) NSInteger channelNum;
@property (nonatomic) NSInteger deviceSubnetID;
@property (nonatomic) NSInteger deviceDeviceID;
@property (nonatomic) NSInteger curState;
@property (nonatomic, copy) NSString * _Nonnull remarks;
@property (nonatomic, copy) NSString * _Nonnull parentRemarks;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull arrCurState;
@property (nonatomic) NSInteger deviceType;
@property (nonatomic, strong) LogicMode * _Nullable logicMode;
@property (nonatomic) NSInteger physicsChannelNum;
@property (nonatomic) BOOL isGetStateSuccess;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK13Configuration")
@interface Configuration : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull UNKNOW_TYPE;)
+ (NSString * _Nonnull)UNKNOW_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger HDL_SDK_DEV_TYPE;)
+ (NSInteger)HDL_SDK_DEV_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LIGTH_BIG_TYPE;)
+ (NSInteger)LIGTH_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CURTAIN_BIG_TYPE;)
+ (NSInteger)CURTAIN_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AIR_BIG_TYPE;)
+ (NSInteger)AIR_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO_BIG_TYPE;)
+ (NSInteger)AUDIO_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_BIG_TYPE;)
+ (NSInteger)LOGIC_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger GLOBAL_LOGIC_BIG_TYPE;)
+ (NSInteger)GLOBAL_LOGIC_BIG_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger SEARCH;)
+ (NSInteger)SEARCH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CONTROL;)
+ (NSInteger)CONTROL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger STATE;)
+ (NSInteger)STATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger REMARKS;)
+ (NSInteger)REMARKS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger HET_DEVICES;)
+ (NSInteger)HET_DEVICES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger Midea_DEVICES;)
+ (NSInteger)Midea_DEVICES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger JAV_DEVICES;)
+ (NSInteger)JAV_DEVICES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger GET_LOGIC_INFO;)
+ (NSInteger)GET_LOGIC_INFO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger XW_DEVICES;)
+ (NSInteger)XW_DEVICES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger WARNING;)
+ (NSInteger)WARNING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO;)
+ (NSInteger)AUDIO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CHANGE;)
+ (NSInteger)RCU_CHANGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_SEARCH;)
+ (NSInteger)RCU_SEARCH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_MODIFY;)
+ (NSInteger)RCU_MODIFY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_READ;)
+ (NSInteger)RCU_READ SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CAST;)
+ (NSInteger)RCU_CAST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger PORT;)
+ (NSInteger)PORT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICES_SEARCH_COMMAND;)
+ (NSInteger)DEVICES_SEARCH_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICES_SEARCH_BACK_COMMAND;)
+ (NSInteger)DEVICES_SEARCH_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICES_READ_COMMAND;)
+ (NSInteger)DEVICES_READ_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEVICES_READ_BACK_COMMAND;)
+ (NSInteger)DEVICES_READ_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LIGHT_CTRL_COMMAND;)
+ (NSInteger)LIGHT_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LIGHT_CTRL_BACK_COMMAND;)
+ (NSInteger)LIGHT_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LIGHT_STATE_COMMAND;)
+ (NSInteger)LIGHT_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LIGHT_STATE_BACK_COMMAND;)
+ (NSInteger)LIGHT_STATE_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CURTAIN_CTRL_COMMAND;)
+ (NSInteger)CURTAIN_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CURTAIN_CTRL_BACK_COMMAND;)
+ (NSInteger)CURTAIN_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CURTAIN_STATE_COMMAND;)
+ (NSInteger)CURTAIN_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger CURTAIN_STATE_BACK_COMMAND;)
+ (NSInteger)CURTAIN_STATE_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AIR_CTRL_COMMAND;)
+ (NSInteger)AIR_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AIR_CTRL_BACK_COMMAND;)
+ (NSInteger)AIR_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AIR_STATE_COMMAND;)
+ (NSInteger)AIR_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AIR_STATE_BACK_COMMAND;)
+ (NSInteger)AIR_STATE_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_GET_INFO;)
+ (NSInteger)LOGIC_GET_INFO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_GET_BACK_INFO;)
+ (NSInteger)LOGIC_GET_BACK_INFO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_CTRL_COMMAND;)
+ (NSInteger)LOGIC_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_CTRL_BACK_COMMAND;)
+ (NSInteger)LOGIC_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_STATE_COMMAND;)
+ (NSInteger)LOGIC_STATE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger LOGIC_STATE_BACK_COMMAND;)
+ (NSInteger)LOGIC_STATE_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger WARNING_COMMAND;)
+ (NSInteger)WARNING_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO_CTRL_READ_COMMAND;)
+ (NSInteger)AUDIO_CTRL_READ_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO_CTRL_READ_BACK_COMMAND;)
+ (NSInteger)AUDIO_CTRL_READ_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger MUSIC2_COMMAND;)
+ (NSInteger)MUSIC2_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger MUSIC3_COMMAND;)
+ (NSInteger)MUSIC3_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO_MenuPlay_INSTRUCTION_COMMAND;)
+ (NSInteger)AUDIO_MenuPlay_INSTRUCTION_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger AUDIO_MenuPlay_INSTRUCTION_BACK_COMMAND;)
+ (NSInteger)AUDIO_MenuPlay_INSTRUCTION_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_SEND_PORT;)
+ (NSInteger)RCU_SEND_PORT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_RECEIVE_PORT;)
+ (NSInteger)RCU_RECEIVE_PORT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RCU_MULTI_IP;)
+ (NSString * _Nonnull)RCU_MULTI_IP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CHANGE_COMMAND;)
+ (NSInteger)RCU_CHANGE_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CHANGE_BACK_COMMAND;)
+ (NSInteger)RCU_CHANGE_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_SERRCH_COMMAND;)
+ (NSInteger)RCU_SERRCH_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_SERRCH_BACK_COMMAND;)
+ (NSInteger)RCU_SERRCH_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_MODIFY_COMMAND;)
+ (NSInteger)RCU_MODIFY_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_MODIFY_BACK_COMMAND;)
+ (NSInteger)RCU_MODIFY_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_READ_SDK_INFO_COMMAND;)
+ (NSInteger)RCU_READ_SDK_INFO_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_READ_SDK_INFO_BACK_COMMAND;)
+ (NSInteger)RCU_READ_SDK_INFO_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_ROOM_CAST_COMMAND;)
+ (NSInteger)RCU_ROOM_CAST_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CURTAIN_CTRL_COMMAND;)
+ (NSInteger)RCU_CURTAIN_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CURTAIN_CTRL_BACK_COMMAND;)
+ (NSInteger)RCU_CURTAIN_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_CURTAIN_CAST_COMMAND;)
+ (NSInteger)RCU_CURTAIN_CAST_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_AIR_CTRL_COMMAND;)
+ (NSInteger)RCU_AIR_CTRL_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_AIR_CTRL_BACK_COMMAND;)
+ (NSInteger)RCU_AIR_CTRL_BACK_COMMAND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger RCU_AIR_CAST_COMMAND;)
+ (NSInteger)RCU_AIR_CAST_COMMAND SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK19CurtainCtrlBackInfo")
@interface CurtainCtrlBackInfo : NSObject
@property (nonatomic) NSInteger num;
@property (nonatomic) NSInteger state;
@property (nonatomic, copy) NSString * _Nonnull remarks;
@property (nonatomic, copy) NSString * _Nonnull parentRemarks;
@property (nonatomic, strong) AppliancesInfo * _Nullable appliancesInfo;
@property (nonatomic) BOOL isSuccessCtrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6HDLSDK19CurtainCtrlDelegate_")
@protocol CurtainCtrlDelegate
- (void)getCurtainCtrlInfoWithCurtainCtrlBackInfo:(CurtainCtrlBackInfo * _Nonnull)curtainCtrlBackInfo;
@end


SWIFT_CLASS("_TtC6HDLSDK17CurtainCtrlParser")
@interface CurtainCtrlParser : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CurtainCtrlParser * _Nonnull shareInstance;)
+ (CurtainCtrlParser * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSInteger curtainPause;
@property (nonatomic, readonly) NSInteger curtainOpen;
@property (nonatomic, readonly) NSInteger curtainClose;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_STATE_PAUSE;)
+ (NSInteger)TYPE_STATE_PAUSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_STATE_OPEN;)
+ (NSInteger)TYPE_STATE_OPEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_STATE_CLOSE;)
+ (NSInteger)TYPE_STATE_CLOSE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// 获取窗帘附加数据
/// \param curtainNum 窗帘号
///
/// \param state 状态值
///
///
/// returns:
/// 窗帘附加数据
- (NSArray<NSNumber *> * _Nonnull)getCurtainAddByteWithCurtainNum:(NSInteger)curtainNum state:(NSInteger)state SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6HDLSDK12DeviceParser")
@interface DeviceParser : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class DevicesStateBackInfo;

SWIFT_PROTOCOL("_TtP6HDLSDK19DeviceStateDelegate_")
@protocol DeviceStateDelegate
- (void)getDevicesStateWithDevicesStateBackInfo:(DevicesStateBackInfo * _Nonnull)devicesStateBackInfo;
@end


SWIFT_CLASS("_TtC6HDLSDK11DevicesData")
@interface DevicesData : NSObject
@property (nonatomic, copy) NSArray<AppliancesInfo *> * _Nonnull appliancesInfoList;
@property (nonatomic) NSInteger sourceSubnetID;
@property (nonatomic) NSInteger sourceDeviceID;
@property (nonatomic, copy) NSString * _Nonnull remark;
@property (nonatomic) BOOL isSuccessGetState;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SearchDevicesBackInfo;

SWIFT_PROTOCOL("_TtP6HDLSDK19DevicesInfoDelegate_")
@protocol DevicesInfoDelegate
- (void)getDevicesDataWithSearchDevicesBackInfo:(SearchDevicesBackInfo * _Nonnull)searchDevicesBackInfo;
@end


SWIFT_CLASS("_TtC6HDLSDK20DevicesStateBackInfo")
@interface DevicesStateBackInfo : NSObject
@property (nonatomic, strong) AppliancesInfo * _Nullable appliancesInfo;
@property (nonatomic) BOOL isSuccess;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK11HDLApConfig")
@interface HDLApConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LIGHT;)
+ (NSInteger)TYPE_LIGHT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LIGHT_DIMMER;)
+ (NSInteger)TYPE_LIGHT_DIMMER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LIGHT_RELAY;)
+ (NSInteger)TYPE_LIGHT_RELAY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LIGHT_MIX_DIMMER;)
+ (NSInteger)TYPE_LIGHT_MIX_DIMMER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LIGHT_MIX_RELAY;)
+ (NSInteger)TYPE_LIGHT_MIX_RELAY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_CURTAIN;)
+ (NSInteger)TYPE_CURTAIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_CURTAIN_GLYSTRO;)
+ (NSInteger)TYPE_CURTAIN_GLYSTRO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_CURTAIN_ROLLER;)
+ (NSInteger)TYPE_CURTAIN_ROLLER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_CURTAIN_MODULE;)
+ (NSInteger)TYPE_CURTAIN_MODULE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_AC;)
+ (NSInteger)TYPE_AC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_AC_HVAC;)
+ (NSInteger)TYPE_AC_HVAC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_AC_PANEL;)
+ (NSInteger)TYPE_AC_PANEL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_MUSIC;)
+ (NSInteger)TYPE_MUSIC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_MUSIC_MODULE;)
+ (NSInteger)TYPE_MUSIC_MODULE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_MUSIC_THIRD_PARTY_MODULE;)
+ (NSInteger)TYPE_MUSIC_THIRD_PARTY_MODULE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LOGIC;)
+ (NSInteger)TYPE_LOGIC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_LOGIC_MODULE;)
+ (NSInteger)TYPE_LOGIC_MODULE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger TYPE_GLOBAL_LOGIC_MODULE;)
+ (NSInteger)TYPE_GLOBAL_LOGIC_MODULE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK10HDLCommand")
@interface HDLCommand : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HDLCommand * _Nonnull shareInstance;)
+ (HDLCommand * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isDevicesSearch;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
/// 提供第三方调用的设备搜索接口
/// \param delegate 委托
///
- (void)devicesSearchWithDelegate:(id _Nonnull)delegate;
/// 提供第三方调用的场景搜索接口
/// \param delegate 委托
///
- (void)scenesSearchWithDelegate:(id _Nonnull)delegate;
/// 第二次搜索
/// \param delegate 委托
///
/// \param arg1 随机数1
///
/// \param arg2 随机数2
///
/// \param devicesDataList 已经搜索到存起来的设备列表
///
- (void)devicesSearch2WithDelegate:(id _Nonnull)delegate arg1:(uint8_t)arg1 arg2:(uint8_t)arg2 devicesDataList:(NSArray<DevicesData *> * _Nonnull)devicesDataList;
- (void)registerDelegateWithDelegate:(id _Nonnull)delegate type:(NSInteger)type;
/// 提供第三方调用的灯光控制接口
/// \param appliancesInfo 设备Bean
///
/// \param state 状态值
///
- (void)lightCtrlWithDelegate:(id _Nonnull)delegate appliancesInfo:(AppliancesInfo * _Nonnull)appliancesInfo state:(NSInteger)state;
/// 提供第三方调用的窗帘控制接口
/// \param appliancesInfo 设备Bean
///
/// \param state 状态值
///
- (void)curtainCtrlWithDelegate:(id _Nonnull)delegate appliancesInfo:(AppliancesInfo * _Nonnull)appliancesInfo state:(NSInteger)state;
/// 提供第三方用的空调控制接口
/// \param appliancesInfo 设备Bean
///
/// \param type 空调模式类型
///
/// \param state 数值
///
- (void)airCtrlWithDelegate:(id _Nonnull)delegate appliancesInfo:(AppliancesInfo * _Nonnull)appliancesInfo ctrlType:(NSInteger)ctrlType state:(NSInteger)state;
/// 提供第三方调用的逻辑控制接口
/// \param appliancesInfo 设备Bean
///
- (void)sceneCtrlWithAppliancesInfo:(AppliancesInfo * _Nonnull)appliancesInfo;
/// 主动获取设备状态
/// \param delegate 委托
///
/// \param appliancesInfo 设备Bean
///
- (void)getDeviceStateWithDelegate:(id _Nonnull)delegate appliancesInfo:(AppliancesInfo * _Nonnull)appliancesInfo;
@property (nonatomic, copy) NSArray<AppliancesInfo *> * _Nonnull stateAppliances;
@property (nonatomic) BOOL isGetAppliancesState;
- (void)getAppliancesStateWithDelegate:(id _Nonnull)delegate appliances:(NSArray<AppliancesInfo *> * _Nonnull)appliances;
- (void)getAllDevicesStateWithDelegate:(id _Nonnull)delegate devicesData:(NSArray<DevicesData *> * _Nonnull)devicesData;
/// 获取设备备注，此方法不提供给第三方使用
/// \param infos 设备信息集
///
- (void)getDevRemarksWithInfos:(NSArray<AppliancesInfo *> * _Nonnull)infos;
/// 自定义发送UDP数据包
/// \param command 操作码
///
/// \param subnetId 子网号
///
/// \param deviceID 设备号
///
/// \param addByte 附加数据
///
- (void)cusSendCommandWithCommand:(NSInteger)command subnetId:(NSInteger)subnetId deviceID:(NSInteger)deviceID addByte:(NSArray<NSNumber *> * _Nonnull)addByte;
@end

@class ListRemarks;
@protocol ScenesInfoDelegate;
@class UdpDataBean;

SWIFT_CLASS("_TtC6HDLSDK10HDLManager")
@interface HDLManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HDLManager * _Nonnull shareInstance;)
+ (HDLManager * _Nonnull)shareInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSArray<DevicesData *> * _Nonnull devicesDataList;
@property (nonatomic, copy) NSArray<DevicesData *> * _Nonnull realDevicesDataList;
@property (nonatomic, copy) NSArray<ListRemarks *> * _Nonnull listRemarkses;
@property (nonatomic, strong) id <DevicesInfoDelegate> _Nullable devicesDelegate;
@property (nonatomic, strong) id <ScenesInfoDelegate> _Nullable scenesDelegate;
@property (nonatomic) BOOL isSearchSuccess;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)initSDK SWIFT_METHOD_FAMILY(none);
- (void)releaseSDK;
/// 处理UDP返回回来的所有数据，并分类处理
/// \param getDatas 数据Bean
///
/// \param type 处理的数据类型
///
- (void)handleWithGetDatas:(UdpDataBean * _Nonnull)getDatas type:(NSInteger)type;
/// 发送第二次搜索
/// \param arg1 随机数1
///
/// \param arg2 随机数2
///
- (void)searchTwiceWithArg1:(uint8_t)arg1 arg2:(uint8_t)arg2;
/// 返回设备数据
- (void)sendDevicesList;
/// 返回场景数据
- (void)sendScenesList;
/// 发送丢失的备注数据
/// \param isDevSearch 是否设备搜索
///
- (void)sendMissRemarksWithIsDevSearch:(BOOL)isDevSearch;
@end

@class GCDAsyncUdpSocket;

SWIFT_CLASS("_TtC6HDLSDK10HDLUdpCore")
@interface HDLUdpCore : NSObject <GCDAsyncUdpSocketDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HDLUdpCore * _Nonnull sharedInstance;)
+ (HDLUdpCore * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (void)initUDP SWIFT_METHOD_FAMILY(none);
- (void)releaseUDP;
- (void)udpSocket:(GCDAsyncUdpSocket * _Null_unspecified)sock didReceiveData:(NSData * _Null_unspecified)data fromAddress:(NSData * _Null_unspecified)address withFilterContext:(id _Null_unspecified)filterContext;
- (void)HandleInsideDataWithUdpData:(UdpDataBean * _Nonnull)udpData;
- (void)udpSocket:(GCDAsyncUdpSocket * _Null_unspecified)sock didNotConnect:(NSError * _Null_unspecified)error;
- (void)udpSocket:(GCDAsyncUdpSocket * _Null_unspecified)sock didSendDataWithTag:(NSInteger)tag;
@end


SWIFT_CLASS("_TtC6HDLSDK17LightCtrlBackInfo")
@interface LightCtrlBackInfo : NSObject
@property (nonatomic, strong) AppliancesInfo * _Nullable appliancesInfo;
@property (nonatomic) NSInteger channelNum;
@property (nonatomic) NSInteger brightness;
@property (nonatomic) NSInteger channelCount;
@property (nonatomic) NSInteger deviceChannelCount;
@property (nonatomic, copy) NSString * _Nonnull remarks;
@property (nonatomic, copy) NSString * _Nonnull parentRemarks;
@property (nonatomic) BOOL isSuccessCtrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6HDLSDK17LightCtrlDelegate_")
@protocol LightCtrlDelegate
- (void)getLightCtrlInfoWithLightCtrlBackInfo:(LightCtrlBackInfo * _Nonnull)lightCtrlBackInfo;
@end


SWIFT_CLASS("_TtC6HDLSDK11ListRemarks")
@interface ListRemarks : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK9LogicMode")
@interface LogicMode : NSObject
@property (nonatomic) NSInteger areaNum;
@property (nonatomic) NSInteger areaSceneNum;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK17SceneCtrlBackInfo")
@interface SceneCtrlBackInfo : NSObject
@property (nonatomic, strong) AppliancesInfo * _Nullable appliancesInfo;
@property (nonatomic) NSInteger areaNum;
@property (nonatomic) NSInteger areaSceneNum;
@property (nonatomic) BOOL isSuccessCtrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP6HDLSDK17SceneCtrlDelegate_")
@protocol SceneCtrlDelegate
- (void)getSceneCtrlInfoWithSceneCtrlBackInfo:(SceneCtrlBackInfo * _Nonnull)sceneCtrlBackInfo;
@end


SWIFT_PROTOCOL("_TtP6HDLSDK18ScenesInfoDelegate_")
@protocol ScenesInfoDelegate
- (void)getScenesDataWithSearchDevicesBackInfo:(SearchDevicesBackInfo * _Nonnull)searchDevicesBackInfo;
@end


SWIFT_CLASS("_TtC6HDLSDK21SearchDevicesBackInfo")
@interface SearchDevicesBackInfo : NSObject
@property (nonatomic, copy) NSArray<DevicesData *> * _Nullable devicesData;
@property (nonatomic) BOOL isSuccess;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6HDLSDK11UdpDataBean")
@interface UdpDataBean : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
